# Generated by Django 3.2.15 on 2022-10-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(default='empty', max_length=10, null=True),
        ),
    ]
