# Generated by Django 3.2.15 on 2022-10-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_alter_post_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, default='P', max_length=10, null=True),
        ),
    ]
