# Generated by Django 3.2.15 on 2022-11-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0002_auto_20221027_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='style_data',
            field=models.TextField(default='', null=True),
        ),
    ]
