# Generated by Django 3.2.15 on 2022-10-18 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0004_delete_share_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=10)),
                ('doc_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.post')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('doc_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharedoc.post')),
            ],
        ),
        migrations.CreateModel(
            name='excel_json_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='empty', max_length=200, null=True)),
                ('json_data', models.TextField(default='empty', null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharedoc.post')),
            ],
        ),
    ]
