# Generated by Django 3.2.15 on 2022-10-21 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharedoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='group_test_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_code', models.CharField(max_length=150, null=True)),
                ('dept_name', models.CharField(max_length=150, null=True)),
                ('parent_code', models.CharField(max_length=150, null=True)),
                ('depth', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_test_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('dept_code', models.ForeignKey(db_column='dept_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharedoc.group_test_table')),
            ],
        ),
    ]
