# Generated by Django 3.2.15 on 2022-10-23 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharedoc', '0002_group_test_table_user_test_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(default='R', max_length=10),
        ),
        migrations.CreateModel(
            name='data_collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_row', models.IntegerField(blank=True, null=True)),
                ('cell_line', models.IntegerField(blank=True, null=True)),
                ('data', models.CharField(max_length=300)),
                ('cell_type', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharedoc.post')),
            ],
        ),
    ]
