# Generated by Django 3.2.15 on 2022-10-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedoc', '0004_auto_20221027_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='memo',
            field=models.TextField(default='', null=True),
        ),
    ]
