# Generated by Django 3.2.15 on 2022-11-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedoc', '0006_auto_20221101_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_test_table',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
